## Epsódio 1

In [1]:
3 + 5*4

23

In [2]:
peso_kg = 15 * 4

In [3]:
peso_kg * .9

54.0

In [4]:
lanchonete = "Bob's"

In [5]:
lanchonete

"Bob's"

In [6]:
jogador = 'Edison "Pelé" do Nascimento'

In [7]:
jogador

'Edison "Pelé" do Nascimento'

In [8]:
peso_kg

60

In [9]:
print(peso_kg)

60


In [10]:
print(lanchonete)

Bob's


In [11]:
x = '60'

In [12]:
y = 60

In [14]:
x + lanchonete

"60Bob's"

In [15]:
print(x, y)

60 60


In [16]:
print(jogador, peso_kg)

Edison "Pelé" do Nascimento 60


In [18]:
texto_peso = 'Peso em kilogramas:'

In [19]:
print(texto_peso, peso_kg)

Peso em kilogramas: 60


In [20]:
print('Peso em libras:', peso_kg * 2.2)

Peso em libras: 132.0


In [21]:
peso_kg

60

In [23]:
peso_kg = 65
print('Peso em kg agora é:', peso_kg)

Peso em kg agora é: 65


In [24]:
peso_lb = 2.2 * peso_kg
print(texto_peso, peso_kg, 'e em libras:', peso_lb)

Peso em kilogramas: 65 e em libras: 143.0


In [26]:
peso_kg = 100.0

In [27]:
print('o peso em kg agora é', peso_kg, 'mas o peso em lb continua', peso_lb)

o peso em kg agora é 100.0 mas o peso em lb continua 143.0


In [28]:
mass = 47.5
age = 122
mass = mass* 2.0
age = age -20
print(mass,age)

95.0 102


In [29]:
mass

95.0

In [30]:
age

102

In [31]:
frist, second = 'Grace', 'Hopper'
third, fourth = second, frist
print(third, fourth)

Hopper Grace


## Epsódio 2

In [34]:
import numpy

In [35]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [36]:
data = numpy.loadtxt(fname='inflammation-01.csv', delimiter=',')

In [37]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [38]:
type(1)

int

In [39]:
type(1.)

float

In [40]:
type('e')

str

In [41]:
type(data)

numpy.ndarray

In [42]:
data.shape

(60, 40)

In [43]:
('first value in data:', data[0, 0])

('first value in data:', 0.0)

In [44]:
data[30, 20]

13.0

In [45]:
[0,3]

[0, 3]

In [46]:
data[0,3]

3.0

In [47]:
[0,2]

[0, 2]

In [48]:
data[0,2]

1.0

In [49]:
numpy.mean(data)

6.14875

In [50]:
import time
print(time.ctime())

Thu Jun 18 21:28:56 2020
